spring:
  cloud:
    function:
      scan:
        packages: org.debugroom.cloud.aws.lambda.dbinit.app.function
cloud:
  aws:
    stack:
      name: ma-common-rds
    credentials:
      instanceProfile: false
      profileName:
    region:
      auto: false
      static: ap-northeast-1
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG