AWSTemplateFormatVersion: '2010-09-09'

Description: S3 Bucket for mattermost template with YAML - S3 Bucket Definition

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ma-mattermost-bucket
      AccessControl: "Private"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  S3Bucket:
    Description: S3 for mattermost storage bucket name
    Value: !Ref S3Bucket
    Export:
      Name: Mattermost-S3Bucket

  S3BucketArn:
    Description: S3 for mattermost storage bucket arn
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: Mattermost-S3Bucket-Arn