AWSTemplateFormatVersion: '2010-09-09'

Description: Custom Resource template with YAML -Custom Resource Depends on vpc-cfn.yml

Parameters:
  VPCName:
    Description: Target VPC Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: ma-common-vpc

Resources:
  LambdaTrigger:
    Type: Custom::LambdaTrigger
    Properties:
      ServiceToken:
        Fn::ImportValue: !Sub ${VPCName}-LamdaForCreatingTableInRdsArn
      Region: !Ref "AWS::Region"
